# Generated by Django 5.2.9 on 2026-01-07 15:50

import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_gateways', '0001_netbox_gateways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
    ]